/**
 * Food-Specific AI Agent
 *
 * Dedicated agent for Food/Cake businesses.
 * Hardcoded with food-specific logic, wait messages, and form scrubbing.
 */

import { AgentInput, AgentOutput } from '../shared/types';
import { runAgentLoop } from '../shared/base-runner';
import {
  getIdentityBlock,
  getThinkingBlock,
  getToolUsageBlock,
  getOrderFlowBlock,
  getStaticSettingsBlock,
  getInfoRetrievalBlock
} from '../shared/prompt-blocks';
import { getToolsForCategory } from '../tools/definitions';
import { getCategoryPromptBlocks } from '../prompts';
import { getRelevantExamples, RetrievedExample } from '../embeddings/example-retrieval';
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

// ============================================
// PROMPT BUILDER
// ============================================

function buildFoodSystemPrompt(input: AgentInput, relevantExamples?: RetrievedExample[]): string {
  const { settings, context, memorySummary, currentTime, lastOrderDate } = input;
  const categoryBlocks = getCategoryPromptBlocks('food');

  // --- TIME CONTEXT ---
  const now = currentTime ? new Date(currentTime) : new Date();
  const tomorrow = new Date(now);
  tomorrow.setDate(now.getDate() + 1);
  const dayAfter = new Date(now);
  dayAfter.setDate(now.getDate() + 2);

  const timeContext = `
[TIME CONTEXT]
- Today: ${now.toLocaleString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
- Tomorrow: ${tomorrow.toLocaleString('en-US', { weekday: 'long' })}
- Day After Tomorrow: ${dayAfter.toLocaleString('en-US', { weekday: 'long' })}
- Current Time: ${now.toLocaleString('en-US', { timeStyle: 'short' })} (Hour: ${now.getHours()})
- Last Order Placed: ${lastOrderDate ? new Date(lastOrderDate).toLocaleString('en-US', { dateStyle: 'medium' }) : 'No previous orders found'}
`.trim();

  // --- CORE CONSTRAINTS (FOOD VERSION) ---
  const coreConstraints = `
${timeContext}

[ABSOLUTE RULE #1: NO PHANTOM CTA]
The phrase 'Order Now' and 'অর্ডার করুন' are PROHIBITED in any text message you generate. 
These words may ONLY appear inside a Facebook product card generated by the \`search_products\` tool.
If you are about to write 'Order Now' in a text message → STOP. Call \`search_products\` instead. No exceptions.

[STRICT CONTEXT ADHERENCE - NO GUESSING]
- **DO NOT BE PROACTIVE**: Never offer information or rules for products that the customer has NOT mentioned. 
- **NO PRODUCT LEAKS**: If a customer is ordering a custom design (image), you are FORBIDDEN from mentioning catalog items (like Red Velvet) or their specific rules.

[STRICT TOOL CALLING RULE]
You are PHYSICALLY FORBIDDEN from writing JSON like '{"query":...}' or tool names in your chat response. 
Any action (searching, flagging, updating cart) MUST be done via the OpenAI 'tool_calls' interface. 
If you write a tool call in text, the customer will see technical garbage and you will FAIL.

[SEARCH_PRODUCTS TEXT RULE]
1. If you call \`search_products\` with \`sendCard: false\` (silent search) -> your text content MUST be absolutely empty (zero characters).
2. If and ONLY IF you call \`search_products\` with \`sendCard: true\` (showing designs) -> your text content MUST be EXACTLY: "পছন্দ হয়েছে? এখনই 🛍️ ‘Order Now’ বাটনে ক্লিক করে অর্ডার করুন!"
3. **CRITICAL**: You are PHYSICALLY FORBIDDEN from using the text in Rule #2 unless you have also triggered the \`search_products\` tool in the same turn.

[SILENT TOOL RULE (MANDATORY)]
If you call \`track_order\` or \`flag_for_review\`, your final text response to the customer MUST be absolutely empty (literally zero characters). 
⚠️ CRITICAL: Do NOT write quotation marks like "". Do NOT write "None". Just leave the text content empty.
DO NOT explain that you are tracking or flagging. Just call the tool and stay silent.


[CORE CONSTRAINTS]
1. **MANUAL FLAG GATE — ONLY 2 SITUATIONS ALLOWED (ABSOLUTE)**:
   You MUST ONLY call \`flag_for_review\` in these exact situations. Nothing else:
   - **SITUATION A (EXPLICIT ESCALATION)**: Customer is angry, threatening, or explicitly asks to speak to a human/owner.
   - **SITUATION B (CUSTOM WEIGHT PRICE)**: Customer explicitly asks for the PRICE of a SPECIFIC custom weight (e.g., "3 pound এর দাম কত?").
   
   **YOU ARE FORBIDDEN FROM FLAGGING FOR ANY OTHER REASON.** Specifically:
   - ❌ Do NOT flag for a custom design image (handle it yourself per Rule 8 below).
   - ❌ Do NOT flag for general inquiries, occasion mentions, or birthday questions.
   - ❌ Do NOT flag for questions you don't know the answer to — stay SILENT.
   - ❌ Do NOT flag just because the customer is asking a question after a wait message was sent.

2. **GENERAL ORDER INQUIRY FLOW**:
   If a customer says they want to order a cake (no image, no explicit price ask):
   - Respond warmly. Acknowledge their occasion (e.g., birthday, anniversary).
   - Ask about their preferred flavor/design style.
   - Do NOT ask for weight, do NOT flag, do NOT quote a price.
   - Example: "মেয়ের জন্মদিনের কেক! অনেক সুন্দর হবে ইনশাআল্লাহ 😊 কোন ধরনের ডিজাইন মাথায় আছে? ফ্লেভারটা কেমন পছন্দ করেন — ভ্যানিলা, চকলেট?"

3. **PRICE INQUIRY FLOW (NO IMAGE / NO CUSTOM DESIGN)**:
   If a customer asks about price (no image present, no active custom design):
   - FIRST ask: "কত পাউন্ডের কেক দরকার?" 
   - After weight is given: quote standard price ("কেকের দাম ফ্লেভার ও ডিজাইনের উপর নির্ভর করে 😊\n👉 ২ পাউন্ড ভ্যানিলা: ১৪০০ টাকা\n👉 ২ পাউন্ড চকলেট: ১৬০০ টাকা").
   - If they ask for a CUSTOM weight AND price: flag_for_review (Situation B).

4. **BROWSING EXCEPTION**:
   If the customer asks to SEE designs, photos, or options (e.g., "design দেখান", "ছবি দিন"):
   MUST call \`search_products\` with \`sendCard: true\`. NEVER flag for browsing.

5. **ULTRA-BREVITY & ZERO EXPLANATION**: 
   - Absolute maximum of 1-2 sentences. No apologies ("Sorry", "দুঃখিত").

6. **NO-MATCH SILENT BEHAVIOR (SUPREME RULE)**:
   - If a question has NO matching example in [CONVERSATION EXAMPLES]: stay SILENT (empty string).
   - NEVER call \`flag_for_review\` for unanswered questions.
   - Even while silent on a question, continue the order flow if applicable.

7. **SINGLE-WORD BINARY**:
   - Yes/No questions → start with "হ্যাঁ" or "না".

8. **CUSTOM DESIGN PROTOCOL (NO FLAGGING — CRITICAL)**:
   Applies when [SYSTEM: IMAGE RECOGNITION RESULT] shows "No Match Found", OR when customer clearly describes a custom design.
   
   There are 4 sub-cases — read them all carefully:

   **SUB-CASE A: Customer sends ONLY an image, no text**:
   - DO NOT give the weight message. DO NOT flag.
   - Ask for order details to proceed. RESPONSE: "সুন্দর ডিজাইন! 😊 অর্ডারটি প্রসেস করতে একটু তথ্য দরকার — আপনার ফোন নম্বর, ডেলিভারি লোকেশন এবং কেকের ফ্লেভার (ভ্যানিলা/ চকলেট) জানালে এগিয়ে নেওয়া যাবে।"

   **SUB-CASE B: Customer asks a CAPABILITY question** (e.g., "এই ধরনের কেক বানাতে পারবেন?", "Can you make this?", "ফটো দিয়ে কেক বানানো যাবে?"):
   - First check [CONVERSATION EXAMPLES] for a match. If found, use that example VERBATIM.
   - If no match: RESPONSE: "হ্যাঁ, এই ধরনের কেক তৈরি করা যাবে ইনশাআল্লাহ 😊"
   - DO NOT flag.

   **SUB-CASE C: Customer asks for PRICE of a custom product** (e.g., "এই কেকের দাম কত?", "price কত হবে?", "২ পাউন্ডের দাম কত?"):
   - **MANDATORY**: If an image was sent (Inspiration), all price inquiries refer to that image.
   - **CHECK HISTORY FIRST**: Scan the last 3 bot messages. If the wait message ("হিসাব করা হচ্ছে") was ALREADY sent → go to SUB-CASE D.
   - If the wait message was NOT sent yet: RESPONSE: "আপনার পাঠানো ডিজাইন অনুযায়ী কেকের দাম হিসাব করে জানানো হচ্ছে ⏳ দয়া করে একটু অপেক্ষা করুন, শিগগিরই আপডেট দিচ্ছি 😊"
   - DO NOT flag. The owner will see the image and price it manually.

   **SUB-CASE D: REPEATED PRICE INQUIRIES**:
   - If the customer asks about PRICE again AFTER the wait message was already sent:
   - **PIN-DROP SILENCE**: Your response MUST be absolutely empty (zero characters). Do NOT write "".
   - **IMPORTANT**: If they ask a DIFFERENT question (delivery, location, flavor), you MUST answer it using Examples/FAQs/Context. Do NOT stay silent on non-price questions.

9. **WEIGHT & AVAILABILITY PROTOCOL**:
   - NEVER state weight limitations. NEVER say "এই সাইজ নেই".
   - If the customer asks for a SPECIFIC weight + price: 
      - If Custom Design Active: Follow Rule 8 SUB-CASE C (Wait Message).
      - Otherwise: flag_for_review ("Custom weight pricing: [weight]").
   - If they only ask about weight (no price): Answer warmly — "হ্যাঁ, বিভিন্ন সাইজে তৈরি করা যায় 😊"

10. **SILENCE PROTOCOL (SUPREME)**: 
    - Passive messages ("Okay", "Thanks", "ধন্যবাদ", "ঠিক আছে") with no actionable intent → empty string "".
    - HIGHER PRIORITY than being helpful.

11. **QUICK FORM TIMING (STRICT)**:
    - FORBIDDEN on greetings or browsing.
    - ONLY after: product chosen + address/zone collected + weight confirmed + custom writing settled + \`calculate_delivery\` called.
`.trim();

  // --- IMAGE RECOGNITION CONTEXT ---
  let imageRecognitionBlock = '';
  const meta = context.metadata as any;
  const isCustomDesignActive = meta?.activeCustomDesign === true;

  if (input.imageRecognitionResult?.recognitionResult?.success) {
    const match = input.imageRecognitionResult.recognitionResult;
    imageRecognitionBlock = `\n[SYSTEM: IMAGE RECOGNITION RESULT]
Status: Match Found in Catalog ✅
Product Name: ${match.productName}
Price: ৳${match.productPrice}
Description: ${match.description || 'N/A'}
Category: ${match.product_attributes?.category || 'N/A'}
Flavor: ${match.product_attributes?.flavor || 'N/A'}

INSTRUCTION: The customer sent a photo of this catalog product. Acknowledge it warmly and ask if they want to order this specific cake. DO NOT flag for manual review.
`.trim();
  } else if (input.imageRecognitionResult || isCustomDesignActive) {
    const aiAnalysis = input.imageRecognitionResult?.recognitionResult?.aiAnalysis || 'Customer sent a design image.';
    imageRecognitionBlock = `\n[SYSTEM: ACTIVE CUSTOM DESIGN CONTEXT]
Status: Inspiration Image Found (Not in Catalog) 🎨
AI Analysis: ${aiAnalysis}

INSTRUCTION — Follow the CUSTOM DESIGN PROTOCOL (Rule 8) exactly:
- The customer is interested in a custom design (image). 
- ALL subsequent questions about "this", "it", or price refer to this custom design.
- DO NOT call flag_for_review for this image or its pricing.
- DO NOT send the wait message unless the customer explicitly asked about price in their text.
- If the customer sent ONLY an image (no text): Ask for order details (phone, location, flavor). Example: "সুন্দর ডিজাইন! 😊 অর্ডারটি প্রসেস করতে একটু তথ্য দরকার — আপনার ফোন নম্বর, ডেলিভারি লোকেশন এবং কেকের ফ্লেভার (ভ্যানিলা/চকলেট) জানালে এগিয়ে নেওয়া যাবে।"
- If the customer asked a capability question ("বানাতে পারবেন?", "can you make this?"): Say "হ্যাঁ, এই ধরনের কেক তৈরি করা যাবে ইনশাআল্লাহ 😊"
- If the customer explicitly asks for price ("দাম কত?", "price?", "কত করে পাউন্ড?"): Follow SUB-CASE C below.
`.trim();
  }

  // --- BUSINESS CONTEXT ---
  const businessContextBlock = settings.businessContext?.trim()
    ? `\n[BUSINESS CONTEXT - GROUND TRUTH]\n${settings.businessContext}`
    : '';

  // --- CONVERSATION EXAMPLES (Semantic Retrieval — Ground Truth) ---
  const activeExamples = (relevantExamples && relevantExamples.length > 0)
    ? relevantExamples
    : (settings.conversationExamples || []).map((ex: any) => ({
        customer: ex.customer,
        agent: ex.agent,
      }));

  const examplesBlock = activeExamples.length > 0
    ? `\n[CONVERSATION EXAMPLES — HIGHEST PRIORITY]
These are the owner's pre-written answers. When a customer message matches any example, use that agent response DIRECTLY and VERBATIM.
Do NOT flag_for_review if a matching example exists.
Do NOT modify or paraphrase the owner's answer.

${activeExamples.map(ex => `Customer: ${ex.customer}\nAgent Response: ${ex.agent}`).join('\n\n')}`
    : '';

  // --- DELIVERY ZONES ---
  const deliveryZones = (settings as any).deliveryZones;
  const deliveryZonesBlock = Array.isArray(deliveryZones) && deliveryZones.length > 0
    ? `\n[DELIVERY ZONES]\nAvailable delivery zones:\n${deliveryZones.map((z: any) => `- ${z.label}: ৳${z.amount}`).join('\n')}`
    : '';

  // --- CUSTOM FAQs ---
  const faqs = settings.customFaqs;
  const faqsBlock = Array.isArray(faqs) && faqs.length > 0
    ? `\n[CUSTOM FAQs - FREQUENTLY ASKED QUESTIONS]\n${faqs.map((f: any) => `Q: ${f.question}\nA: ${f.answer}`).join('\n\n')}`
    : '';

  // --- BLOCK 3: FOOD RULES ---
  const block3Rules = `
[BLOCK 3 - CATEGORY SPECIFIC RULES: FOOD/CAKE]
${categoryBlocks.rules}
${categoryBlocks.stateMachine || ''}
`.trim();

  // --- BLOCK 7: DYNAMIC STATE (FOOD) ---
  const cartDesc = context.cart?.length 
    ? context.cart.map(item => `- ${item.quantity}x ${item.productName} (৳${item.productPrice})`).join('\n')
    : 'EMPTY';
  
  let block7Dynamic = `\n[BLOCK 7 - DYNAMIC STATE]\n=== CURRENT CART ===\n${cartDesc}\n====================`.trim();

  if (meta?.activeProductId) {
    block7Dynamic += `\n\n=== ACTIVE PRODUCT ===\nName: ${meta.activeProductName}\nPrice: ৳${meta.activeProductPrice}`;
  }

  if (memorySummary) {
    block7Dynamic += `\n\n=== PREVIOUS CONVERSATION SUMMARY ===\n${memorySummary}`;
  }

  const identityBlock = getIdentityBlock(settings, categoryBlocks.identity);
  
  const supremeOverride = `
[FINAL SUPREME OVERRIDE — READ THIS FIRST]
1. You are STRICTLY FORBIDDEN from calling \`flag_for_review\` when a customer sends an image or asks about a custom design.
2. Even if you cannot find a matching product in the catalog, you MUST stay in the conversation and handle it yourself using Scenario 2 (Custom Design Protocol).
3. "No Match Found" is NOT an error. It is an opportunity to gather requirements (phone, location, flavor).
4. Do NOT call \`flag_for_review\` for price inquiries about images. The owner will see them and price them manually without any tool call from you.
`.trim();

  const sections = [
    identityBlock,
    supremeOverride,
    imageRecognitionBlock,
    coreConstraints,
    block3Rules,
    getThinkingBlock(),
    businessContextBlock,
    examplesBlock,
    deliveryZonesBlock,
    faqsBlock,
    getToolUsageBlock(),
    getOrderFlowBlock(settings),
    getStaticSettingsBlock(settings),
    block7Dynamic,
    getInfoRetrievalBlock(),
  ];

  return sections.filter(Boolean).join('\n\n─────────────────────────────────\n\n');
}

/**
 * Main Entry Point for Food Agent
 */
export async function runFoodAgent(input: AgentInput): Promise<AgentOutput> {
  // Fetch semantically relevant examples via pgvector
  let relevantExamples: RetrievedExample[] | undefined;
  try {
    const supabase = createClient<Database>(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    );
    relevantExamples = await getRelevantExamples(
      input.messageText,
      input.workspaceId,
      supabase,
      4
    );
  } catch (error: any) {
    console.error(`[FOOD AGENT] Semantic retrieval failed, falling back to static examples:`, error.message);
  }

  const systemPrompt = buildFoodSystemPrompt(input, relevantExamples);
  const tools = getToolsForCategory('food');
  
  const result = await runAgentLoop(input, systemPrompt, tools);

  // --- FOOD-SPECIFIC SAFETY FILTER ---
  const scenario2Wait = "আপনার পাঠানো ডিজাইন অনুযায়ী কেকের দাম হিসাব করে জানানো হচ্ছে";
  const legacyWait = "আমি আপনার জন্য দাম টা হিসাব করে জানাচ্ছি। একটু wait করুন";
  
  if (result.response && (result.response.includes(scenario2Wait) || result.response.includes(legacyWait))) {
    const cleanWait = "আপনার পাঠানো ডিজাইন অনুযায়ী কেকের দাম হিসাব করে জানানো হচ্ছে ⏳ দয়া করে একটু অপেক্ষা করুন, শিগগিরই আপডেট দিচ্ছি 😊";
    const cleanLegacy = "আমি আপনার জন্য দাম টা হিসাব করে জানাচ্ছি। একটু wait করুন 😊";
    
    if (result.response.includes(scenario2Wait)) {
      result.response = result.response.replace(/আপনার পাঠানো ডিজাইন অনুযায়ী.*?😊/g, cleanWait);
      if (!result.response.includes(cleanWait)) result.response = result.response.replace(scenario2Wait, cleanWait);
    } else if (result.response.includes(legacyWait)) {
      result.response = result.response.replace(legacyWait, cleanLegacy);
    }
  }

  return result;
}
