/**
 * Food-Specific AI Agent
 *
 * Dedicated agent for Food/Cake businesses.
 * Hardcoded with food-specific logic, wait messages, and form scrubbing.
 */

import { AgentInput, AgentOutput } from '../shared/types';
import { runAgentLoop } from '../shared/base-runner';
import {
  getIdentityBlock,
  getThinkingBlock,
  getToolUsageBlock,
  getOrderFlowBlock,
  getStaticSettingsBlock,
  getInfoRetrievalBlock
} from '../shared/prompt-blocks';
import { getToolsForCategory } from '../tools/definitions';
import { getCategoryPromptBlocks } from '../prompts';
import { getRelevantExamples, RetrievedExample } from '../embeddings/example-retrieval';
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

// ============================================
// PROMPT BUILDER
// ============================================

function buildFoodSystemPrompt(input: AgentInput, relevantExamples?: RetrievedExample[]): string {
  const { settings, context, memorySummary, currentTime, lastOrderDate } = input;
  const categoryBlocks = getCategoryPromptBlocks('food');

  // --- TIME CONTEXT ---
  const now = currentTime ? new Date(currentTime) : new Date();
  const tomorrow = new Date(now);
  tomorrow.setDate(now.getDate() + 1);
  const dayAfter = new Date(now);
  dayAfter.setDate(now.getDate() + 2);

  const timeContext = `
[TIME CONTEXT]
- Today: ${now.toLocaleString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
- Tomorrow: ${tomorrow.toLocaleString('en-US', { weekday: 'long' })}
- Day After Tomorrow: ${dayAfter.toLocaleString('en-US', { weekday: 'long' })}
- Current Time: ${now.toLocaleString('en-US', { timeStyle: 'short' })} (Hour: ${now.getHours()})
- Last Order Placed: ${lastOrderDate ? new Date(lastOrderDate).toLocaleString('en-US', { dateStyle: 'medium' }) : 'No previous orders found'}
`.trim();

  // --- CORE CONSTRAINTS (FOOD VERSION) ---
  const coreConstraints = `
${timeContext}

[ABSOLUTE RULE #1: NO PHANTOM CTA]
The phrase 'Order Now' and 'অর্ডার করুন' are PROHIBITED in any text message you generate. 
These words may ONLY appear inside a Facebook product card generated by the \`search_products\` tool.
If you are about to write 'Order Now' in a text message → STOP. Call \`search_products\` instead. No exceptions.

[STRICT CONTEXT ADHERENCE - NO GUESSING]
- **DO NOT BE PROACTIVE**: Never offer information or rules for products that the customer has NOT mentioned. 
- **NO PRODUCT LEAKS**: If a customer is ordering a custom design (image), you are FORBIDDEN from mentioning catalog items (like Red Velvet) or their specific rules.

[STRICT TOOL CALLING RULE]
You are PHYSICALLY FORBIDDEN from writing JSON like '{"query":...}' or tool names in your chat response. 
Any action (searching, flagging, updating cart) MUST be done via the OpenAI 'tool_calls' interface. 
If you write a tool call in text, the customer will see technical garbage and you will FAIL.

[SEARCH_PRODUCTS TEXT RULE]
1. If you call \`search_products\` with \`sendCard: false\` (silent search) -> your text content MUST be absolutely empty (zero characters).
2. If and ONLY IF you call \`search_products\` with \`sendCard: true\` (showing designs) -> your text content MUST be EXACTLY: "পছন্দ হয়েছে? এখনই 🛍️ ‘Order Now’ বাটনে ক্লিক করে অর্ডার করুন!"
3. **CRITICAL**: You are PHYSICALLY FORBIDDEN from using the text in Rule #2 unless you have also triggered the \`search_products\` tool in the same turn.

[SILENT TOOL RULE (MANDATORY)]
If you call \`track_order\` or \`flag_for_review\`, your final text response to the customer MUST be absolutely empty (literally zero characters). 
⚠️ CRITICAL: Do NOT write quotation marks like "". Do NOT write "None". Just leave the text content empty.
DO NOT explain that you are tracking or flagging. Just call the tool and stay silent.


[CORE CONSTRAINTS]
1. **IMAGE SILENCE PROTOCOL (RULE 1 & 5)**: 
   - If the customer sends ONLY an image (or multiple images) and [SYSTEM: IMAGE RECOGNITION RESULT] shows "No Match Found" or "Inspiration Found" -> Your response MUST be an empty string "". 
   - DO NOT acknowledge the image. DO NOT ask "সুন্দর ডিজাইন, অর্ডার করবেন?". Stay silent and wait for their intent.

2. **CUSTOMIZATION ACKNOWLEDGMENT (RULE 2)**:
   - When a customer describes colors, themes, or says "এভাবে বানাতে হবে" / "এই ডিজাইনটা চাচ্ছি":
   - **ACTION**: Acknowledge warmly and briefly: "হ্যাঁ এটা করতে পারব ইনশাআল্লাহ 😊"
   - **FOLLOW UP**: Ask for all details at once: "আপনার সব ডিজাইন ডিটেইলস (ফ্লেভার, কত পাউন্ড, কোনো লেখা থাকবে কি না) একবারে লিখে দিলে আমাদের জন্য সুবিধা হয় 🙏"
   - **STRICT PROHIBITION**: DO NOT ask for phone number. DO NOT ask for address. DO NOT trigger any order tools. Keep it purely to design discussion.

3. **PRICE WAIT MESSAGE — ONE TIME ONLY (RULE 3)**:
   - When the customer explicitly asks for a price of a custom design:
   - **CHECK**: Scan [BLOCK 7 - DYNAMIC STATE] for \`waitMessageSent: true\`.
   - **IF TRUE**: Return an empty string "". DO NOT repeat the wait message.
   - **IF FALSE**: Send EXACTLY: "আপনার ডিজাইন অনুযায়ী দাম হিসাব করে জানাচ্ছি ⏳ এর মধ্যে আর কিছু জানার থাকলে জিজ্ঞেস করতে পারেন 😊"
   - **ACTION**: You MUST call \`update_customer_info\` with a dummy field or metadata if possible to mark intent, but the system will primarily track this via your response content.

4. **CONVERSATION HISTORY CHECK — ANTI-REPEAT (RULE 4)**:
   - Before finalizing your text, read the last 5 messages from "Bot" in the conversation history.
   - If your current response is semantically similar (even with different words) to any of those 5 messages -> Your response MUST be an empty string "".
   - Never say the same thing twice in a row.

5. **STYLISTIC MIRRORING (CRITICAL)**:
   - When you find a match in [CONVERSATION EXAMPLES], your response MUST copy the **Agent's style, Banglish ratio, and brevity** exactly.
   - Use the example's answer as your primary source for the "How" of the response.
   - Synthesis Result: If you identify the customer's intent as a match for an example, use the example's text as the core of your response.

─────────────────────────────────

[CUSTOM DESIGN PROTOCOL - SCENARIO 2]
Applies when an image is sent with no catalog match.

**CASE A: Image-only message (No text)**
- **RESPONSE**: "" (Empty string).
- **REASON**: Rule 1. Wait for customer to speak.

**CASE B: Capability Inquiry ("বানাতে পারবেন?", "এই ডিজাইন হবে?")**
- **RESPONSE**: "হ্যাঁ, এই ধরনের কেক তৈরি করা যাবে ইনশাআল্লাহ 😊 আপনার সব ডিজাইন ডিটেইলস একবারে লিখে দিলে আমাদের জন্য সুবিধা হয় 🙏"
- **STRICT**: No order flow.

**CASE C: Price Inquiry ("দাম কত?", "price কত?")**
- **IF \`waitMessageSent\` is TRUE**: RESPONSE: "" (Empty string).
- **IF \`waitMessageSent\` is FALSE**: RESPONSE: "আপনার ডিজাইন অনুযায়ী দাম হিসাব করে জানাচ্ছি ⏳ এর মধ্যে আর কিছু জানার থাকলে জিজ্ঞেস করতে পারেন 😊"

**CASE D: Repeated/Passive content**
- If customer says "ok", "thanks", "wow" -> RESPONSE: "" (Empty string).

9. **WEIGHT & AVAILABILITY PROTOCOL**:
   - NEVER state weight limitations. NEVER say "এই সাইজ নেই".
   - If the customer asks for a SPECIFIC weight + price: 
      - If Custom Design Active: Follow Rule 8 SUB-CASE C (Wait Message).
      - Otherwise: flag_for_review ("Custom weight pricing: [weight]").
   - If they only ask about weight (no price): Answer warmly — "হ্যাঁ, বিভিন্ন সাইজে তৈরি করা যায় 😊"

10. **SILENCE PROTOCOL (SUPREME)**: 
    - Passive messages ("Okay", "Thanks", "ধন্যবাদ", "ঠিক আছে") with no actionable intent → empty string "".
    - HIGHER PRIORITY than being helpful.

11. **QUICK FORM TIMING (STRICT)**:
    - FORBIDDEN on greetings or browsing.
    - ONLY after: product chosen + address/zone collected + weight confirmed + custom writing settled + \`calculate_delivery\` called.
`.trim();

  // --- IMAGE RECOGNITION CONTEXT ---
  let imageRecognitionBlock = '';
  const meta = context.metadata as any;
  const isCustomDesignActive = meta?.activeCustomDesign === true;

  if (input.imageRecognitionResult?.recognitionResult?.success) {
    const match = input.imageRecognitionResult.recognitionResult;
    imageRecognitionBlock = `\n[SYSTEM: IMAGE RECOGNITION RESULT]
Status: Match Found in Catalog ✅
Product Name: ${match.productName}
Price: ৳${match.productPrice}
Description: ${match.description || 'N/A'}
Category: ${match.product_attributes?.category || 'N/A'}
Flavor: ${match.product_attributes?.flavor || 'N/A'}

INSTRUCTION: The customer sent a photo of this catalog product. Acknowledge it warmly and ask if they want to order this specific cake. DO NOT flag for manual review.
`.trim();
  } else if (input.imageRecognitionResult || isCustomDesignActive) {
    const aiAnalysis = input.imageRecognitionResult?.recognitionResult?.aiAnalysis || 'Customer sent a design image.';
    imageRecognitionBlock = `\n[SYSTEM: ACTIVE CUSTOM DESIGN CONTEXT]
Status: Inspiration Image Found (Not in Catalog) 🎨
AI Analysis: ${aiAnalysis}

INSTRUCTION — Follow the CUSTOM DESIGN PROTOCOL exactly:
- The customer is interested in a custom design (image). 
- If the customer sent ONLY an image (no text): Your response MUST be "". (Rule 1).
- If the customer asked a capability question ("বানাতে পারবেন?", "can you make this?"): Say "হ্যাঁ, এই ধরনের কেক তৈরি করা যাবে ইনশাআল্লাহ 😊 আপনার সব ডিজাইন ডিটেইলস একবারে লিখে দিলে আমাদের জন্য সুবিধা হয় 🙏"
- If they ask for price: Follow Case C (Wait Message).
- DO NOT ask for phone/address yet.
`.trim();
  }

  // --- BUSINESS CONTEXT ---
  const businessContextBlock = settings.businessContext?.trim()
    ? `\n[BUSINESS CONTEXT - GROUND TRUTH]\n${settings.businessContext}`
    : '';

  // --- CONVERSATION EXAMPLES (Semantic Retrieval — Ground Truth) ---
  const activeExamples = (relevantExamples && relevantExamples.length > 0)
    ? relevantExamples
    : (settings.conversationExamples || []).map((ex: any) => ({
        customer: ex.customer,
        agent: ex.agent,
      }));

  const examplesBlock = activeExamples.length > 0
    ? `\n[CONVERSATION EXAMPLES — HIGHEST PRIORITY]
These are the owner's pre-written answers. When a customer message matches any example, use that agent response DIRECTLY and VERBATIM.
Do NOT flag_for_review if a matching example exists.
Do NOT modify or paraphrase the owner's answer.

${activeExamples.map(ex => `Customer: ${ex.customer}\nAgent Response: ${ex.agent}`).join('\n\n')}`
    : '';

  // --- DELIVERY ZONES ---
  const deliveryZones = (settings as any).deliveryZones;
  const deliveryZonesBlock = Array.isArray(deliveryZones) && deliveryZones.length > 0
    ? `\n[DELIVERY ZONES]\nAvailable delivery zones:\n${deliveryZones.map((z: any) => `- ${z.label}: ৳${z.amount}`).join('\n')}`
    : '';

  // --- CUSTOM FAQs ---
  const faqs = settings.customFaqs;
  const faqsBlock = Array.isArray(faqs) && faqs.length > 0
    ? `\n[CUSTOM FAQs - FREQUENTLY ASKED QUESTIONS]\n${faqs.map((f: any) => `Q: ${f.question}\nA: ${f.answer}`).join('\n\n')}`
    : '';

  // --- BLOCK 3: FOOD RULES ---
  const block3Rules = `
[BLOCK 3 - CATEGORY SPECIFIC RULES: FOOD/CAKE]
${categoryBlocks.rules}
${categoryBlocks.stateMachine || ''}
`.trim();

  // --- BLOCK 7: DYNAMIC STATE (FOOD) ---
  const cartDesc = context.cart?.length 
    ? context.cart.map(item => `- ${item.quantity}x ${item.productName} (৳${item.productPrice})`).join('\n')
    : 'EMPTY';
  
  // Rule 3: Detect if wait message was already sent (using a robust pattern check)
  const waitMessageSent = (input.conversationHistory || []).some(m => {
    if (m.role !== 'assistant' || typeof m.content !== 'string') return false;
    return /দাম হিসাব করে|দাম জানানো হচ্ছে|হিসাব করে জানাচ্ছি/.test(m.content);
  });

  // Rule 2: Detect if capability acknowledgment was already sent
  const capabilityAckSent = (input.conversationHistory || []).some(m => {
    if (m.role !== 'assistant' || typeof m.content !== 'string') return false;
    return /এই ধরনের কেক তৈরি করা যাবে|ডিজাইন ডিটেইলস একবারে লিখে দিলে/.test(m.content);
  });

  let block7Dynamic = `\n[BLOCK 7 - DYNAMIC STATE]\n=== CURRENT CART ===\n${cartDesc}\n====================\nwaitMessageSent: ${waitMessageSent}\ncapabilityAckSent: ${capabilityAckSent}`.trim();

  if (meta?.activeProductId) {
    block7Dynamic += `\n\n=== ACTIVE PRODUCT ===\nName: ${meta.activeProductName}\nPrice: ৳${meta.activeProductPrice}`;
  }

  if (memorySummary) {
    block7Dynamic += `\n\n=== PREVIOUS CONVERSATION SUMMARY ===\n${memorySummary}`;
  }

  const identityBlock = getIdentityBlock(settings, categoryBlocks.identity);
  
  const supremeOverride = `
[FINAL SUPREME OVERRIDE — READ THIS FIRST]
1. **INTENT IDENTIFICATION (TOP PRIORITY)**: 
   - You MUST read the last 5 messages to identify what the customer is talking about.
   - If a custom design (image/description) was discussed recently, and the customer asks "দাম কত?" or "price?", they are referring to THAT custom design.

2. **PRICE WAIT MESSAGE (ONE-TIME ONLY)**:
   - If the customer asks for PRICE of a custom design:
   - IF \`waitMessageSent\` is TRUE: Your response MUST be an empty string "". DO NOT repeat the wait message.
   - IF \`waitMessageSent\` is FALSE: Send EXACTLY: "আপনার ডিজাইন অনুযায়ী দাম হিসাব করে জানাচ্ছি ⏳ এর মধ্যে আর কিছু জানার থাকলে জিজ্ঞেস করতে পারেন 😊"
   - This rule is absolute. Even if they ask 10 times, you only answer once.

3. **CAPABILITY ACKNOWLEDGMENT (ONE-TIME ONLY)**:
   - If the customer asks "Can you do this?" or sends design details:
   - IF \`capabilityAckSent\` is TRUE: Be extremely brief. Response: "জি ইনশাআল্লাহ করা যাবে" or "ঠিক আছে, বুঝতে পেরেছি 😊".
   - IF \`capabilityAckSent\` is FALSE: Send "হ্যাঁ, এই ধরনের কেক তৈরি করা যাবে ইনশাআল্লাহ 😊 আপনার সব ডিজাইন ডিটেইলস একবারে লিখে দিলে আমাদের জন্য সুবিধা হয় 🙏"

4. You are STRICTLY FORBIDDEN from calling \`flag_for_review\` for custom designs.
5. "No Match Found" is NOT an error. Handle it yourself using Scenario 2.
`.trim();

  const sections = [
    identityBlock,
    supremeOverride,
    imageRecognitionBlock,
    coreConstraints,
    block3Rules,
    getThinkingBlock(),
    businessContextBlock,
    examplesBlock,
    deliveryZonesBlock,
    faqsBlock,
    getToolUsageBlock(),
    getOrderFlowBlock(settings),
    getStaticSettingsBlock(settings),
    block7Dynamic,
    getInfoRetrievalBlock(),
  ];

  return sections.filter(Boolean).join('\n\n─────────────────────────────────\n\n');
}

/**
 * Main Entry Point for Food Agent
 */
export async function runFoodAgent(input: AgentInput): Promise<AgentOutput> {
  // Fetch semantically relevant examples via pgvector
  let relevantExamples: RetrievedExample[] | undefined;
  try {
    const supabase = createClient<Database>(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!,
      { auth: { autoRefreshToken: false, persistSession: false } }
    );
    relevantExamples = await getRelevantExamples(
      input.messageText,
      input.workspaceId,
      supabase,
      4
    );
  } catch (error: any) {
    console.error(`[FOOD AGENT] Semantic retrieval failed, falling back to static examples:`, error.message);
  }

  const systemPrompt = buildFoodSystemPrompt(input, relevantExamples);
  const tools = getToolsForCategory('food');
  
  const result = await runAgentLoop(input, systemPrompt, tools);

  // --- FOOD-SPECIFIC SAFETY FILTER ---
  const scenario2Wait = "আপনার পাঠানো ডিজাইন অনুযায়ী কেকের দাম হিসাব করে জানানো হচ্ছে";
  const legacyWait = "আমি আপনার জন্য দাম টা হিসাব করে জানাচ্ছি। একটু wait করুন";
  
  if (result.response && (result.response.includes(scenario2Wait) || result.response.includes(legacyWait))) {
    const cleanWait = "আপনার পাঠানো ডিজাইন অনুযায়ী কেকের দাম হিসাব করে জানানো হচ্ছে ⏳ দয়া করে একটু অপেক্ষা করুন, শিগগিরই আপডেট দিচ্ছি 😊";
    const cleanLegacy = "আমি আপনার জন্য দাম টা হিসাব করে জানাচ্ছি। একটু wait করুন 😊";
    
    if (result.response.includes(scenario2Wait)) {
      result.response = result.response.replace(/আপনার পাঠানো ডিজাইন অনুযায়ী.*?😊/g, cleanWait);
      if (!result.response.includes(cleanWait)) result.response = result.response.replace(scenario2Wait, cleanWait);
    } else if (result.response.includes(legacyWait)) {
      result.response = result.response.replace(legacyWait, cleanLegacy);
    }
  }

  return result;
}
