-- Migration: Add Memory Summary to Conversations
-- Purpose: Store compressed summaries of older messages to reduce token usage
--          in AI agent calls. Part of the agentic refactor (Step 1).
-- Date: 2026-03-05

-- Add memory summary column for conversation history compression
ALTER TABLE conversations
ADD COLUMN IF NOT EXISTS memory_summary TEXT,
ADD COLUMN IF NOT EXISTS memory_summarized_at TIMESTAMPTZ;

-- No index needed — this column is only read when loading a specific conversation
-- by ID, which is already indexed via the primary key.

-- Add comments for documentation
COMMENT ON COLUMN conversations.memory_summary IS 'Compressed summary of older messages (10+) to reduce token usage in AI calls. Generated by gpt-4o-mini.';
COMMENT ON COLUMN conversations.memory_summarized_at IS 'Timestamp of last summarization. Used to determine if re-summarization is needed.';
