/**
 * Transactional Message Templates
 *
 * Renders the 3 critical transactional messages that must NEVER
 * be generated by the AI. These are exact templates from workspace
 * settings with dynamic placeholder replacement.
 *
 * The AI must not produce order confirmations, payment instructions,
 * or cancellation messages. The orchestrator calls this module
 * after save_order succeeds.
 *
 * @module lib/ai/tools/transactional-messages
 */

import { WorkspaceSettings } from '@/lib/workspace/settings-cache';

// ============================================
// TYPES
// ============================================

export interface OrderData {
  orderNumber: string;
  totalAmount: number;
  subtotal: number;
  deliveryCharge: number;
  customerName: string;
  itemCount: number;
}

export interface TransactionalMessages {
  orderConfirmed: string;
  paymentInstructions: string | null;
}

// ============================================
// MAIN FUNCTIONS
// ============================================

/**
 * Renders the order confirmation and payment instructions messages.
 *
 * Called by the orchestrator AFTER save_order returns success.
 * These messages are sent directly via Facebook Messenger —
 * the AI agent never sees or generates them.
 *
 * @param settings - Workspace settings containing templates and payment config
 * @param orderData - Order details for placeholder replacement
 * @returns Rendered messages ready to send
 */
export function renderOrderConfirmationMessages(
  settings: WorkspaceSettings,
  orderData: OrderData
): TransactionalMessages {
  const templates = settings.fastLaneMessages;

  // ========================================
  // 1. ORDER CONFIRMED MESSAGE
  // ========================================

  const orderConfirmed = templates.orderConfirmed
    || 'আলহামদুলিল্লাহ! আপনার অর্ডারটি গ্রহণ করা হয়েছে। ✅\n\n'
     + 'আমরা ২৪ ঘণ্টার মধ্যে call দিয়ে সব কনফার্ম করব ইনশাআল্লাহ। 📞\n\n'
     + 'আমাদের সাথে কেনাকাটার জন্য ধন্যবাদ! 🙏';

  // ========================================
  // 2. PAYMENT INSTRUCTIONS MESSAGE
  // ========================================

  const paymentDetails = buildPaymentDetails(settings);

  let paymentInstructions: string | null = null;

  if (paymentDetails) {
    const rawTemplate = templates.paymentInstructions
      || '💰 পেমেন্ট ডিটেইলস:\n'
       + '{paymentNumber}\n\n'
       + 'ডেলিভারি চার্জ ৳{deliveryCharge} টাকা advance পাঠিয়ে শেষের ২ ডিজিট পাঠান। 🔢';

    paymentInstructions = rawTemplate
      .replace(/\{deliveryCharge\}/g, String(orderData.deliveryCharge))
      .replace(/\{orderNumber\}/g, orderData.orderNumber)
      .replace(/\{name\}/g, orderData.customerName)
      .replace(/\{itemCount\}/g, String(orderData.itemCount))
      .replace(/\{paymentNumber\}/g, paymentDetails)
      .replace(/\{\{PAYMENT_DETAILS\}\}/g, paymentDetails);
    
    // Safety Override: For payment instructions, we ALWAYS want to ask for the delivery charge 
    // as an advance fee, even if the user accidentally uses {totalAmount} in their template.
    paymentInstructions = paymentInstructions
      .replace(/\{totalAmount\}/g, String(orderData.deliveryCharge))
      .replace(/\{subtotal\}/g, String(orderData.deliveryCharge));
  }

  return {
    orderConfirmed,
    paymentInstructions,
  };
}

/**
 * Renders the order cancellation message.
 *
 * Called by the orchestrator when the customer cancels mid-flow
 * or when the AI calls a cart-clearing action.
 *
 * @param settings - Workspace settings containing the cancellation template
 * @returns Rendered cancellation message
 */
export function renderOrderCancelledMessage(
  settings: WorkspaceSettings
): string {
  return settings.fastLaneMessages.orderCancelled
    || 'অর্ডার cancel করা হয়েছে। 😊\n\n'
     + 'কোনো সমস্যা নেই! নতুন অর্ডার করতে product এর ছবি পাঠান।';
}

// ============================================
// HELPERS
// ============================================

/**
 * Builds a formatted payment details string from workspace settings.
 *
 * Iterates through enabled payment methods (bkash, nagad)
 * and formats them as a numbered list. Returns null if no
 * payment methods are enabled (which means COD-only or misconfigured).
 *
 * Example output:
 *   "📱 bKash: 01712345678\n📱 Nagad: 01898765432"
 */
function buildPaymentDetails(settings: WorkspaceSettings): string | null {
  const methods = settings.paymentMethods;
  const lines: string[] = [];

  if (methods.bkash?.enabled && methods.bkash.number) {
    lines.push(`📱 bKash: ${methods.bkash.number}`);
  }

  if (methods.nagad?.enabled && methods.nagad.number) {
    lines.push(`📱 Nagad: ${methods.nagad.number}`);
  }

  if (lines.length === 0) {
    return null;
  }

  return lines.join('\n');
}
